// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_logs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_logs (project_id, user_id, action, entity_type, entity_id, changes, ip_address)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, project_id, user_id, action, entity_type, entity_id, changes, ip_address, created_at
`

type CreateAuditLogParams struct {
	ProjectID  pgtype.UUID `json:"project_id"`
	UserID     pgtype.UUID `json:"user_id"`
	Action     string      `json:"action"`
	EntityType string      `json:"entity_type"`
	EntityID   pgtype.UUID `json:"entity_id"`
	Changes    []byte      `json:"changes"`
	IpAddress  pgtype.Text `json:"ip_address"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.ProjectID,
		arg.UserID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.Changes,
		arg.IpAddress,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Action,
		&i.EntityType,
		&i.EntityID,
		&i.Changes,
		&i.IpAddress,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditLogsByEntity = `-- name: ListAuditLogsByEntity :many
SELECT id, project_id, user_id, action, entity_type, entity_id, changes, ip_address, created_at FROM audit_logs
WHERE project_id = $1 AND entity_type = $2 AND entity_id = $3
ORDER BY created_at DESC
`

type ListAuditLogsByEntityParams struct {
	ProjectID  pgtype.UUID `json:"project_id"`
	EntityType string      `json:"entity_type"`
	EntityID   pgtype.UUID `json:"entity_id"`
}

func (q *Queries) ListAuditLogsByEntity(ctx context.Context, arg ListAuditLogsByEntityParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsByEntity, arg.ProjectID, arg.EntityType, arg.EntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.UserID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Changes,
			&i.IpAddress,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsByProject = `-- name: ListAuditLogsByProject :many
SELECT al.id, al.project_id, al.user_id, al.action, al.entity_type, al.entity_id, al.changes, al.ip_address, al.created_at, u.wallet_address, u.display_name
FROM audit_logs al
LEFT JOIN users u ON u.id = al.user_id
WHERE al.project_id = $1
ORDER BY al.created_at DESC
LIMIT $2 OFFSET $3
`

type ListAuditLogsByProjectParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

type ListAuditLogsByProjectRow struct {
	ID            pgtype.UUID        `json:"id"`
	ProjectID     pgtype.UUID        `json:"project_id"`
	UserID        pgtype.UUID        `json:"user_id"`
	Action        string             `json:"action"`
	EntityType    string             `json:"entity_type"`
	EntityID      pgtype.UUID        `json:"entity_id"`
	Changes       []byte             `json:"changes"`
	IpAddress     pgtype.Text        `json:"ip_address"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	WalletAddress pgtype.Text        `json:"wallet_address"`
	DisplayName   pgtype.Text        `json:"display_name"`
}

func (q *Queries) ListAuditLogsByProject(ctx context.Context, arg ListAuditLogsByProjectParams) ([]ListAuditLogsByProjectRow, error) {
	rows, err := q.db.Query(ctx, listAuditLogsByProject, arg.ProjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditLogsByProjectRow{}
	for rows.Next() {
		var i ListAuditLogsByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.UserID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Changes,
			&i.IpAddress,
			&i.CreatedAt,
			&i.WalletAddress,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
