// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth_nonces.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteExpiredNonces = `-- name: DeleteExpiredNonces :exec
DELETE FROM auth_nonces WHERE expires_at <= NOW()
`

func (q *Queries) DeleteExpiredNonces(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredNonces)
	return err
}

const deleteNonce = `-- name: DeleteNonce :exec
DELETE FROM auth_nonces WHERE wallet_address = $1
`

func (q *Queries) DeleteNonce(ctx context.Context, walletAddress string) error {
	_, err := q.db.Exec(ctx, deleteNonce, walletAddress)
	return err
}

const getNonce = `-- name: GetNonce :one
SELECT wallet_address, nonce, expires_at, created_at FROM auth_nonces
WHERE wallet_address = $1 AND expires_at > NOW()
`

func (q *Queries) GetNonce(ctx context.Context, walletAddress string) (AuthNonce, error) {
	row := q.db.QueryRow(ctx, getNonce, walletAddress)
	var i AuthNonce
	err := row.Scan(
		&i.WalletAddress,
		&i.Nonce,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const upsertNonce = `-- name: UpsertNonce :one
INSERT INTO auth_nonces (wallet_address, nonce, expires_at)
VALUES ($1, $2, $3)
ON CONFLICT (wallet_address) DO UPDATE
    SET nonce = $2, expires_at = $3
RETURNING wallet_address, nonce, expires_at, created_at
`

type UpsertNonceParams struct {
	WalletAddress string             `json:"wallet_address"`
	Nonce         string             `json:"nonce"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) UpsertNonce(ctx context.Context, arg UpsertNonceParams) (AuthNonce, error) {
	row := q.db.QueryRow(ctx, upsertNonce, arg.WalletAddress, arg.Nonce, arg.ExpiresAt)
	var i AuthNonce
	err := row.Scan(
		&i.WalletAddress,
		&i.Nonce,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
