// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: campaign_analytics_snapshots.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLatestSnapshot = `-- name: GetLatestSnapshot :one
SELECT id, campaign_id, participant_count, task_completion_rate, sybil_flagged_count, claim_rate, tokens_claimed, snapshot_at FROM campaign_analytics_snapshots
WHERE campaign_id = $1
ORDER BY snapshot_at DESC
LIMIT 1
`

func (q *Queries) GetLatestSnapshot(ctx context.Context, campaignID pgtype.UUID) (CampaignAnalyticsSnapshot, error) {
	row := q.db.QueryRow(ctx, getLatestSnapshot, campaignID)
	var i CampaignAnalyticsSnapshot
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.ParticipantCount,
		&i.TaskCompletionRate,
		&i.SybilFlaggedCount,
		&i.ClaimRate,
		&i.TokensClaimed,
		&i.SnapshotAt,
	)
	return i, err
}

const insertAnalyticsSnapshot = `-- name: InsertAnalyticsSnapshot :one
INSERT INTO campaign_analytics_snapshots (
    campaign_id, participant_count, task_completion_rate,
    sybil_flagged_count, claim_rate, tokens_claimed
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, campaign_id, participant_count, task_completion_rate, sybil_flagged_count, claim_rate, tokens_claimed, snapshot_at
`

type InsertAnalyticsSnapshotParams struct {
	CampaignID         pgtype.UUID    `json:"campaign_id"`
	ParticipantCount   pgtype.Int4    `json:"participant_count"`
	TaskCompletionRate pgtype.Numeric `json:"task_completion_rate"`
	SybilFlaggedCount  pgtype.Int4    `json:"sybil_flagged_count"`
	ClaimRate          pgtype.Numeric `json:"claim_rate"`
	TokensClaimed      pgtype.Numeric `json:"tokens_claimed"`
}

func (q *Queries) InsertAnalyticsSnapshot(ctx context.Context, arg InsertAnalyticsSnapshotParams) (CampaignAnalyticsSnapshot, error) {
	row := q.db.QueryRow(ctx, insertAnalyticsSnapshot,
		arg.CampaignID,
		arg.ParticipantCount,
		arg.TaskCompletionRate,
		arg.SybilFlaggedCount,
		arg.ClaimRate,
		arg.TokensClaimed,
	)
	var i CampaignAnalyticsSnapshot
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.ParticipantCount,
		&i.TaskCompletionRate,
		&i.SybilFlaggedCount,
		&i.ClaimRate,
		&i.TokensClaimed,
		&i.SnapshotAt,
	)
	return i, err
}

const listSnapshotsByCampaign = `-- name: ListSnapshotsByCampaign :many
SELECT id, campaign_id, participant_count, task_completion_rate, sybil_flagged_count, claim_rate, tokens_claimed, snapshot_at FROM campaign_analytics_snapshots
WHERE campaign_id = $1
ORDER BY snapshot_at ASC
`

func (q *Queries) ListSnapshotsByCampaign(ctx context.Context, campaignID pgtype.UUID) ([]CampaignAnalyticsSnapshot, error) {
	rows, err := q.db.Query(ctx, listSnapshotsByCampaign, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CampaignAnalyticsSnapshot{}
	for rows.Next() {
		var i CampaignAnalyticsSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.ParticipantCount,
			&i.TaskCompletionRate,
			&i.SybilFlaggedCount,
			&i.ClaimRate,
			&i.TokensClaimed,
			&i.SnapshotAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSnapshotsInRange = `-- name: ListSnapshotsInRange :many
SELECT id, campaign_id, participant_count, task_completion_rate, sybil_flagged_count, claim_rate, tokens_claimed, snapshot_at FROM campaign_analytics_snapshots
WHERE campaign_id = $1
  AND snapshot_at BETWEEN $2 AND $3
ORDER BY snapshot_at ASC
`

type ListSnapshotsInRangeParams struct {
	CampaignID   pgtype.UUID        `json:"campaign_id"`
	SnapshotAt   pgtype.Timestamptz `json:"snapshot_at"`
	SnapshotAt_2 pgtype.Timestamptz `json:"snapshot_at_2"`
}

func (q *Queries) ListSnapshotsInRange(ctx context.Context, arg ListSnapshotsInRangeParams) ([]CampaignAnalyticsSnapshot, error) {
	rows, err := q.db.Query(ctx, listSnapshotsInRange, arg.CampaignID, arg.SnapshotAt, arg.SnapshotAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CampaignAnalyticsSnapshot{}
	for rows.Next() {
		var i CampaignAnalyticsSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.ParticipantCount,
			&i.TaskCompletionRate,
			&i.SybilFlaggedCount,
			&i.ClaimRate,
			&i.TokensClaimed,
			&i.SnapshotAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
