// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: campaigns.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCampaign = `-- name: CreateCampaign :one
INSERT INTO campaigns (
    project_id, title, slug, description, banner_url,
    chain, token_contract, token_symbol, token_decimals,
    total_allocation, reward_type, reward_config,
    eligibility_rules, start_date, end_date, claim_window_days
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9,
    $10, $11, $12,
    $13, $14, $15, $16
)
RETURNING id, project_id, title, slug, description, banner_url, chain, token_contract, token_symbol, token_decimals, total_allocation, claimed_amount, reward_type, reward_config, eligibility_rules, start_date, end_date, claim_window_days, vesting_type, vesting_days, gas_sponsored, merkle_root, claim_contract, deploy_tx_hash, status, finalized_at, completed_at, cancelled_at, deleted_at, created_at, updated_at
`

type CreateCampaignParams struct {
	ProjectID        pgtype.UUID        `json:"project_id"`
	Title            string             `json:"title"`
	Slug             string             `json:"slug"`
	Description      pgtype.Text        `json:"description"`
	BannerUrl        pgtype.Text        `json:"banner_url"`
	Chain            string             `json:"chain"`
	TokenContract    string             `json:"token_contract"`
	TokenSymbol      pgtype.Text        `json:"token_symbol"`
	TokenDecimals    pgtype.Int4        `json:"token_decimals"`
	TotalAllocation  pgtype.Numeric     `json:"total_allocation"`
	RewardType       RewardType         `json:"reward_type"`
	RewardConfig     []byte             `json:"reward_config"`
	EligibilityRules []byte             `json:"eligibility_rules"`
	StartDate        pgtype.Timestamptz `json:"start_date"`
	EndDate          pgtype.Timestamptz `json:"end_date"`
	ClaimWindowDays  int32              `json:"claim_window_days"`
}

func (q *Queries) CreateCampaign(ctx context.Context, arg CreateCampaignParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, createCampaign,
		arg.ProjectID,
		arg.Title,
		arg.Slug,
		arg.Description,
		arg.BannerUrl,
		arg.Chain,
		arg.TokenContract,
		arg.TokenSymbol,
		arg.TokenDecimals,
		arg.TotalAllocation,
		arg.RewardType,
		arg.RewardConfig,
		arg.EligibilityRules,
		arg.StartDate,
		arg.EndDate,
		arg.ClaimWindowDays,
	)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.BannerUrl,
		&i.Chain,
		&i.TokenContract,
		&i.TokenSymbol,
		&i.TokenDecimals,
		&i.TotalAllocation,
		&i.ClaimedAmount,
		&i.RewardType,
		&i.RewardConfig,
		&i.EligibilityRules,
		&i.StartDate,
		&i.EndDate,
		&i.ClaimWindowDays,
		&i.VestingType,
		&i.VestingDays,
		&i.GasSponsored,
		&i.MerkleRoot,
		&i.ClaimContract,
		&i.DeployTxHash,
		&i.Status,
		&i.FinalizedAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const finalizeCampaign = `-- name: FinalizeCampaign :one
UPDATE campaigns SET
    status         = 'distributing',
    merkle_root    = $2,
    claim_contract = $3,
    deploy_tx_hash = $4,
    finalized_at   = NOW()
WHERE id = $1
AND status = 'ended'
RETURNING id, project_id, title, slug, description, banner_url, chain, token_contract, token_symbol, token_decimals, total_allocation, claimed_amount, reward_type, reward_config, eligibility_rules, start_date, end_date, claim_window_days, vesting_type, vesting_days, gas_sponsored, merkle_root, claim_contract, deploy_tx_hash, status, finalized_at, completed_at, cancelled_at, deleted_at, created_at, updated_at
`

type FinalizeCampaignParams struct {
	ID            pgtype.UUID `json:"id"`
	MerkleRoot    pgtype.Text `json:"merkle_root"`
	ClaimContract pgtype.Text `json:"claim_contract"`
	DeployTxHash  pgtype.Text `json:"deploy_tx_hash"`
}

func (q *Queries) FinalizeCampaign(ctx context.Context, arg FinalizeCampaignParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, finalizeCampaign,
		arg.ID,
		arg.MerkleRoot,
		arg.ClaimContract,
		arg.DeployTxHash,
	)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.BannerUrl,
		&i.Chain,
		&i.TokenContract,
		&i.TokenSymbol,
		&i.TokenDecimals,
		&i.TotalAllocation,
		&i.ClaimedAmount,
		&i.RewardType,
		&i.RewardConfig,
		&i.EligibilityRules,
		&i.StartDate,
		&i.EndDate,
		&i.ClaimWindowDays,
		&i.VestingType,
		&i.VestingDays,
		&i.GasSponsored,
		&i.MerkleRoot,
		&i.ClaimContract,
		&i.DeployTxHash,
		&i.Status,
		&i.FinalizedAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCampaignByID = `-- name: GetCampaignByID :one
SELECT id, project_id, title, slug, description, banner_url, chain, token_contract, token_symbol, token_decimals, total_allocation, claimed_amount, reward_type, reward_config, eligibility_rules, start_date, end_date, claim_window_days, vesting_type, vesting_days, gas_sponsored, merkle_root, claim_contract, deploy_tx_hash, status, finalized_at, completed_at, cancelled_at, deleted_at, created_at, updated_at FROM campaigns
WHERE id = $1
AND deleted_at IS NULL
`

func (q *Queries) GetCampaignByID(ctx context.Context, id pgtype.UUID) (Campaign, error) {
	row := q.db.QueryRow(ctx, getCampaignByID, id)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.BannerUrl,
		&i.Chain,
		&i.TokenContract,
		&i.TokenSymbol,
		&i.TokenDecimals,
		&i.TotalAllocation,
		&i.ClaimedAmount,
		&i.RewardType,
		&i.RewardConfig,
		&i.EligibilityRules,
		&i.StartDate,
		&i.EndDate,
		&i.ClaimWindowDays,
		&i.VestingType,
		&i.VestingDays,
		&i.GasSponsored,
		&i.MerkleRoot,
		&i.ClaimContract,
		&i.DeployTxHash,
		&i.Status,
		&i.FinalizedAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCampaignBySlug = `-- name: GetCampaignBySlug :one
SELECT id, project_id, title, slug, description, banner_url, chain, token_contract, token_symbol, token_decimals, total_allocation, claimed_amount, reward_type, reward_config, eligibility_rules, start_date, end_date, claim_window_days, vesting_type, vesting_days, gas_sponsored, merkle_root, claim_contract, deploy_tx_hash, status, finalized_at, completed_at, cancelled_at, deleted_at, created_at, updated_at FROM campaigns
WHERE slug = $1
AND deleted_at IS NULL
`

func (q *Queries) GetCampaignBySlug(ctx context.Context, slug string) (Campaign, error) {
	row := q.db.QueryRow(ctx, getCampaignBySlug, slug)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.BannerUrl,
		&i.Chain,
		&i.TokenContract,
		&i.TokenSymbol,
		&i.TokenDecimals,
		&i.TotalAllocation,
		&i.ClaimedAmount,
		&i.RewardType,
		&i.RewardConfig,
		&i.EligibilityRules,
		&i.StartDate,
		&i.EndDate,
		&i.ClaimWindowDays,
		&i.VestingType,
		&i.VestingDays,
		&i.GasSponsored,
		&i.MerkleRoot,
		&i.ClaimContract,
		&i.DeployTxHash,
		&i.Status,
		&i.FinalizedAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementClaimedAmount = `-- name: IncrementClaimedAmount :one
UPDATE campaigns SET
    claimed_amount = claimed_amount + $2
WHERE id = $1
RETURNING id, project_id, title, slug, description, banner_url, chain, token_contract, token_symbol, token_decimals, total_allocation, claimed_amount, reward_type, reward_config, eligibility_rules, start_date, end_date, claim_window_days, vesting_type, vesting_days, gas_sponsored, merkle_root, claim_contract, deploy_tx_hash, status, finalized_at, completed_at, cancelled_at, deleted_at, created_at, updated_at
`

type IncrementClaimedAmountParams struct {
	ID            pgtype.UUID    `json:"id"`
	ClaimedAmount pgtype.Numeric `json:"claimed_amount"`
}

func (q *Queries) IncrementClaimedAmount(ctx context.Context, arg IncrementClaimedAmountParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, incrementClaimedAmount, arg.ID, arg.ClaimedAmount)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.BannerUrl,
		&i.Chain,
		&i.TokenContract,
		&i.TokenSymbol,
		&i.TokenDecimals,
		&i.TotalAllocation,
		&i.ClaimedAmount,
		&i.RewardType,
		&i.RewardConfig,
		&i.EligibilityRules,
		&i.StartDate,
		&i.EndDate,
		&i.ClaimWindowDays,
		&i.VestingType,
		&i.VestingDays,
		&i.GasSponsored,
		&i.MerkleRoot,
		&i.ClaimContract,
		&i.DeployTxHash,
		&i.Status,
		&i.FinalizedAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveCampaigns = `-- name: ListActiveCampaigns :many
SELECT id, project_id, title, slug, description, banner_url, chain, token_contract, token_symbol, token_decimals, total_allocation, claimed_amount, reward_type, reward_config, eligibility_rules, start_date, end_date, claim_window_days, vesting_type, vesting_days, gas_sponsored, merkle_root, claim_contract, deploy_tx_hash, status, finalized_at, completed_at, cancelled_at, deleted_at, created_at, updated_at FROM campaigns
WHERE status = 'active'
AND chain = COALESCE($3, chain)
AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListActiveCampaignsParams struct {
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
	Chain  pgtype.Text `json:"chain"`
}

func (q *Queries) ListActiveCampaigns(ctx context.Context, arg ListActiveCampaignsParams) ([]Campaign, error) {
	rows, err := q.db.Query(ctx, listActiveCampaigns, arg.Limit, arg.Offset, arg.Chain)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Campaign{}
	for rows.Next() {
		var i Campaign
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.BannerUrl,
			&i.Chain,
			&i.TokenContract,
			&i.TokenSymbol,
			&i.TokenDecimals,
			&i.TotalAllocation,
			&i.ClaimedAmount,
			&i.RewardType,
			&i.RewardConfig,
			&i.EligibilityRules,
			&i.StartDate,
			&i.EndDate,
			&i.ClaimWindowDays,
			&i.VestingType,
			&i.VestingDays,
			&i.GasSponsored,
			&i.MerkleRoot,
			&i.ClaimContract,
			&i.DeployTxHash,
			&i.Status,
			&i.FinalizedAt,
			&i.CompletedAt,
			&i.CancelledAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCampaignsByProject = `-- name: ListCampaignsByProject :many
SELECT id, project_id, title, slug, description, banner_url, chain, token_contract, token_symbol, token_decimals, total_allocation, claimed_amount, reward_type, reward_config, eligibility_rules, start_date, end_date, claim_window_days, vesting_type, vesting_days, gas_sponsored, merkle_root, claim_contract, deploy_tx_hash, status, finalized_at, completed_at, cancelled_at, deleted_at, created_at, updated_at FROM campaigns
WHERE project_id = $1
AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListCampaignsByProject(ctx context.Context, projectID pgtype.UUID) ([]Campaign, error) {
	rows, err := q.db.Query(ctx, listCampaignsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Campaign{}
	for rows.Next() {
		var i Campaign
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.BannerUrl,
			&i.Chain,
			&i.TokenContract,
			&i.TokenSymbol,
			&i.TokenDecimals,
			&i.TotalAllocation,
			&i.ClaimedAmount,
			&i.RewardType,
			&i.RewardConfig,
			&i.EligibilityRules,
			&i.StartDate,
			&i.EndDate,
			&i.ClaimWindowDays,
			&i.VestingType,
			&i.VestingDays,
			&i.GasSponsored,
			&i.MerkleRoot,
			&i.ClaimContract,
			&i.DeployTxHash,
			&i.Status,
			&i.FinalizedAt,
			&i.CompletedAt,
			&i.CancelledAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteCampaign = `-- name: SoftDeleteCampaign :exec
UPDATE campaigns
SET deleted_at = NOW()
WHERE id = $1
AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteCampaign(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteCampaign, id)
	return err
}

const updateCampaign = `-- name: UpdateCampaign :one
UPDATE campaigns SET
    title             = COALESCE($2, title),
    description       = COALESCE($3, description),
    banner_url        = COALESCE($4, banner_url),
    reward_config     = COALESCE($5, reward_config),
    eligibility_rules = COALESCE($6, eligibility_rules),
    start_date        = COALESCE($7, start_date),
    end_date          = COALESCE($8, end_date),
    claim_window_days = COALESCE($9, claim_window_days)
WHERE id = $1
AND status = 'draft'
AND deleted_at IS NULL
RETURNING id, project_id, title, slug, description, banner_url, chain, token_contract, token_symbol, token_decimals, total_allocation, claimed_amount, reward_type, reward_config, eligibility_rules, start_date, end_date, claim_window_days, vesting_type, vesting_days, gas_sponsored, merkle_root, claim_contract, deploy_tx_hash, status, finalized_at, completed_at, cancelled_at, deleted_at, created_at, updated_at
`

type UpdateCampaignParams struct {
	ID               pgtype.UUID        `json:"id"`
	Title            string             `json:"title"`
	Description      pgtype.Text        `json:"description"`
	BannerUrl        pgtype.Text        `json:"banner_url"`
	RewardConfig     []byte             `json:"reward_config"`
	EligibilityRules []byte             `json:"eligibility_rules"`
	StartDate        pgtype.Timestamptz `json:"start_date"`
	EndDate          pgtype.Timestamptz `json:"end_date"`
	ClaimWindowDays  int32              `json:"claim_window_days"`
}

func (q *Queries) UpdateCampaign(ctx context.Context, arg UpdateCampaignParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, updateCampaign,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.BannerUrl,
		arg.RewardConfig,
		arg.EligibilityRules,
		arg.StartDate,
		arg.EndDate,
		arg.ClaimWindowDays,
	)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.BannerUrl,
		&i.Chain,
		&i.TokenContract,
		&i.TokenSymbol,
		&i.TokenDecimals,
		&i.TotalAllocation,
		&i.ClaimedAmount,
		&i.RewardType,
		&i.RewardConfig,
		&i.EligibilityRules,
		&i.StartDate,
		&i.EndDate,
		&i.ClaimWindowDays,
		&i.VestingType,
		&i.VestingDays,
		&i.GasSponsored,
		&i.MerkleRoot,
		&i.ClaimContract,
		&i.DeployTxHash,
		&i.Status,
		&i.FinalizedAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCampaignStatus = `-- name: UpdateCampaignStatus :one
UPDATE campaigns
SET status = $2
WHERE id = $1
AND deleted_at IS NULL
RETURNING id, project_id, title, slug, description, banner_url, chain, token_contract, token_symbol, token_decimals, total_allocation, claimed_amount, reward_type, reward_config, eligibility_rules, start_date, end_date, claim_window_days, vesting_type, vesting_days, gas_sponsored, merkle_root, claim_contract, deploy_tx_hash, status, finalized_at, completed_at, cancelled_at, deleted_at, created_at, updated_at
`

type UpdateCampaignStatusParams struct {
	ID     pgtype.UUID    `json:"id"`
	Status CampaignStatus `json:"status"`
}

func (q *Queries) UpdateCampaignStatus(ctx context.Context, arg UpdateCampaignStatusParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, updateCampaignStatus, arg.ID, arg.Status)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.BannerUrl,
		&i.Chain,
		&i.TokenContract,
		&i.TokenSymbol,
		&i.TokenDecimals,
		&i.TotalAllocation,
		&i.ClaimedAmount,
		&i.RewardType,
		&i.RewardConfig,
		&i.EligibilityRules,
		&i.StartDate,
		&i.EndDate,
		&i.ClaimWindowDays,
		&i.VestingType,
		&i.VestingDays,
		&i.GasSponsored,
		&i.MerkleRoot,
		&i.ClaimContract,
		&i.DeployTxHash,
		&i.Status,
		&i.FinalizedAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
