// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type CampaignStatus string

const (
	CampaignStatusDraft        CampaignStatus = "draft"
	CampaignStatusActive       CampaignStatus = "active"
	CampaignStatusPaused       CampaignStatus = "paused"
	CampaignStatusEnded        CampaignStatus = "ended"
	CampaignStatusDistributing CampaignStatus = "distributing"
	CampaignStatusCompleted    CampaignStatus = "completed"
	CampaignStatusCancelled    CampaignStatus = "cancelled"
)

func (e *CampaignStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CampaignStatus(s)
	case string:
		*e = CampaignStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CampaignStatus: %T", src)
	}
	return nil
}

type NullCampaignStatus struct {
	CampaignStatus CampaignStatus `json:"campaign_status"`
	Valid          bool           `json:"valid"` // Valid is true if CampaignStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCampaignStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CampaignStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CampaignStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCampaignStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CampaignStatus), nil
}

type CompletionStatus string

const (
	CompletionStatusPending  CompletionStatus = "pending"
	CompletionStatusVerified CompletionStatus = "verified"
	CompletionStatusRejected CompletionStatus = "rejected"
)

func (e *CompletionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CompletionStatus(s)
	case string:
		*e = CompletionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CompletionStatus: %T", src)
	}
	return nil
}

type NullCompletionStatus struct {
	CompletionStatus CompletionStatus `json:"completion_status"`
	Valid            bool             `json:"valid"` // Valid is true if CompletionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCompletionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CompletionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CompletionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCompletionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CompletionStatus), nil
}

type RewardType string

const (
	RewardTypeFlat   RewardType = "flat"
	RewardTypePoints RewardType = "points"
	RewardTypeTiered RewardType = "tiered"
)

func (e *RewardType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RewardType(s)
	case string:
		*e = RewardType(s)
	default:
		return fmt.Errorf("unsupported scan type for RewardType: %T", src)
	}
	return nil
}

type NullRewardType struct {
	RewardType RewardType `json:"reward_type"`
	Valid      bool       `json:"valid"` // Valid is true if RewardType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRewardType) Scan(value interface{}) error {
	if value == nil {
		ns.RewardType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RewardType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRewardType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RewardType), nil
}

type VestingType string

const (
	VestingTypeInstant VestingType = "instant"
	VestingTypeLinear  VestingType = "linear"
)

func (e *VestingType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VestingType(s)
	case string:
		*e = VestingType(s)
	default:
		return fmt.Errorf("unsupported scan type for VestingType: %T", src)
	}
	return nil
}

type NullVestingType struct {
	VestingType VestingType `json:"vesting_type"`
	Valid       bool        `json:"valid"` // Valid is true if VestingType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVestingType) Scan(value interface{}) error {
	if value == nil {
		ns.VestingType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VestingType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVestingType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VestingType), nil
}

type AuditLog struct {
	ID         pgtype.UUID        `json:"id"`
	ProjectID  pgtype.UUID        `json:"project_id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Action     string             `json:"action"`
	EntityType string             `json:"entity_type"`
	EntityID   pgtype.UUID        `json:"entity_id"`
	Changes    []byte             `json:"changes"`
	IpAddress  pgtype.Text        `json:"ip_address"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type AuthNonce struct {
	WalletAddress string             `json:"wallet_address"`
	Nonce         string             `json:"nonce"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Campaign struct {
	ID               pgtype.UUID        `json:"id"`
	ProjectID        pgtype.UUID        `json:"project_id"`
	Title            string             `json:"title"`
	Slug             string             `json:"slug"`
	Description      pgtype.Text        `json:"description"`
	BannerUrl        pgtype.Text        `json:"banner_url"`
	Chain            string             `json:"chain"`
	TokenContract    string             `json:"token_contract"`
	TokenSymbol      pgtype.Text        `json:"token_symbol"`
	TokenDecimals    pgtype.Int4        `json:"token_decimals"`
	TotalAllocation  pgtype.Numeric     `json:"total_allocation"`
	ClaimedAmount    pgtype.Numeric     `json:"claimed_amount"`
	RewardType       RewardType         `json:"reward_type"`
	RewardConfig     []byte             `json:"reward_config"`
	EligibilityRules []byte             `json:"eligibility_rules"`
	StartDate        pgtype.Timestamptz `json:"start_date"`
	EndDate          pgtype.Timestamptz `json:"end_date"`
	ClaimWindowDays  int32              `json:"claim_window_days"`
	VestingType      VestingType        `json:"vesting_type"`
	VestingDays      int32              `json:"vesting_days"`
	GasSponsored     bool               `json:"gas_sponsored"`
	MerkleRoot       pgtype.Text        `json:"merkle_root"`
	ClaimContract    pgtype.Text        `json:"claim_contract"`
	DeployTxHash     pgtype.Text        `json:"deploy_tx_hash"`
	Status           CampaignStatus     `json:"status"`
	FinalizedAt      pgtype.Timestamptz `json:"finalized_at"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
	CancelledAt      pgtype.Timestamptz `json:"cancelled_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type CampaignAnalyticsSnapshot struct {
	ID                 pgtype.UUID        `json:"id"`
	CampaignID         pgtype.UUID        `json:"campaign_id"`
	ParticipantCount   pgtype.Int4        `json:"participant_count"`
	TaskCompletionRate pgtype.Numeric     `json:"task_completion_rate"`
	SybilFlaggedCount  pgtype.Int4        `json:"sybil_flagged_count"`
	ClaimRate          pgtype.Numeric     `json:"claim_rate"`
	TokensClaimed      pgtype.Numeric     `json:"tokens_claimed"`
	SnapshotAt         pgtype.Timestamptz `json:"snapshot_at"`
}

type Project struct {
	ID                pgtype.UUID        `json:"id"`
	CompanyName       string             `json:"company_name"`
	EmployeeCount     pgtype.Text        `json:"employee_count"`
	DiscoverySource   pgtype.Text        `json:"discovery_source"`
	Name              string             `json:"name"`
	Slug              string             `json:"slug"`
	Description       pgtype.Text        `json:"description"`
	LogoUrl           pgtype.Text        `json:"logo_url"`
	WebsiteUrl        pgtype.Text        `json:"website_url"`
	TwitterHandle     pgtype.Text        `json:"twitter_handle"`
	DiscordInviteLink pgtype.Text        `json:"discord_invite_link"`
	TreasuryWallet    string             `json:"treasury_wallet"`
	Blockchain        string             `json:"blockchain"`
	Environment       string             `json:"environment"`
	TokenAddress      string             `json:"token_address"`
	TokenName         pgtype.Text        `json:"token_name"`
	TokenSymbol       pgtype.Text        `json:"token_symbol"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type ProjectApiKey struct {
	ID         pgtype.UUID        `json:"id"`
	ProjectID  pgtype.UUID        `json:"project_id"`
	Name       string             `json:"name"`
	KeyHash    string             `json:"key_hash"`
	KeyHint    string             `json:"key_hint"`
	IsActive   bool               `json:"is_active"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
}

type ProjectMember struct {
	ID        pgtype.UUID        `json:"id"`
	ProjectID pgtype.UUID        `json:"project_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Role      string             `json:"role"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Task struct {
	ID               pgtype.UUID        `json:"id"`
	CampaignID       pgtype.UUID        `json:"campaign_id"`
	Title            string             `json:"title"`
	Description      pgtype.Text        `json:"description"`
	TaskType         string             `json:"task_type"`
	VerificationType string             `json:"verification_type"`
	Config           []byte             `json:"config"`
	Points           int32              `json:"points"`
	IsRequired       bool               `json:"is_required"`
	DisplayOrder     int32              `json:"display_order"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type TaskCompletion struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	TaskID       pgtype.UUID        `json:"task_id"`
	CampaignID   pgtype.UUID        `json:"campaign_id"`
	Status       CompletionStatus   `json:"status"`
	PointsEarned int32              `json:"points_earned"`
	Proof        []byte             `json:"proof"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
}

type User struct {
	ID            pgtype.UUID        `json:"id"`
	WalletAddress string             `json:"wallet_address"`
	EnsName       pgtype.Text        `json:"ens_name"`
	DisplayName   pgtype.Text        `json:"display_name"`
	AvatarUrl     pgtype.Text        `json:"avatar_url"`
	UserType      string             `json:"user_type"`
	TwitterID     pgtype.Text        `json:"twitter_id"`
	TwitterHandle pgtype.Text        `json:"twitter_handle"`
	DiscordID     pgtype.Text        `json:"discord_id"`
	DiscordHandle pgtype.Text        `json:"discord_handle"`
	DiscordToken  pgtype.Text        `json:"discord_token"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	LastSeen      pgtype.Timestamptz `json:"last_seen"`
}
