// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (
    company_name, employee_count, discovery_source,
    name, slug, description, logo_url, website_url,
    twitter_handle, discord_invite_link,
    treasury_wallet, blockchain, environment,
    token_address, token_name, token_symbol
) VALUES (
    $1, $2, $3,
    $4, $5, $6, $7, $8,
    $9, $10,
    $11, $12, $13,
    $14, $15, $16
)
RETURNING id, company_name, employee_count, discovery_source, name, slug, description, logo_url, website_url, twitter_handle, discord_invite_link, treasury_wallet, blockchain, environment, token_address, token_name, token_symbol, created_at, updated_at
`

type CreateProjectParams struct {
	CompanyName       string      `json:"company_name"`
	EmployeeCount     pgtype.Text `json:"employee_count"`
	DiscoverySource   pgtype.Text `json:"discovery_source"`
	Name              string      `json:"name"`
	Slug              string      `json:"slug"`
	Description       pgtype.Text `json:"description"`
	LogoUrl           pgtype.Text `json:"logo_url"`
	WebsiteUrl        pgtype.Text `json:"website_url"`
	TwitterHandle     pgtype.Text `json:"twitter_handle"`
	DiscordInviteLink pgtype.Text `json:"discord_invite_link"`
	TreasuryWallet    string      `json:"treasury_wallet"`
	Blockchain        string      `json:"blockchain"`
	Environment       string      `json:"environment"`
	TokenAddress      string      `json:"token_address"`
	TokenName         pgtype.Text `json:"token_name"`
	TokenSymbol       pgtype.Text `json:"token_symbol"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.CompanyName,
		arg.EmployeeCount,
		arg.DiscoverySource,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.LogoUrl,
		arg.WebsiteUrl,
		arg.TwitterHandle,
		arg.DiscordInviteLink,
		arg.TreasuryWallet,
		arg.Blockchain,
		arg.Environment,
		arg.TokenAddress,
		arg.TokenName,
		arg.TokenSymbol,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.CompanyName,
		&i.EmployeeCount,
		&i.DiscoverySource,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.LogoUrl,
		&i.WebsiteUrl,
		&i.TwitterHandle,
		&i.DiscordInviteLink,
		&i.TreasuryWallet,
		&i.Blockchain,
		&i.Environment,
		&i.TokenAddress,
		&i.TokenName,
		&i.TokenSymbol,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, company_name, employee_count, discovery_source, name, slug, description, logo_url, website_url, twitter_handle, discord_invite_link, treasury_wallet, blockchain, environment, token_address, token_name, token_symbol, created_at, updated_at FROM projects WHERE id = $1
`

func (q *Queries) GetProjectByID(ctx context.Context, id pgtype.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.CompanyName,
		&i.EmployeeCount,
		&i.DiscoverySource,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.LogoUrl,
		&i.WebsiteUrl,
		&i.TwitterHandle,
		&i.DiscordInviteLink,
		&i.TreasuryWallet,
		&i.Blockchain,
		&i.Environment,
		&i.TokenAddress,
		&i.TokenName,
		&i.TokenSymbol,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectBySlug = `-- name: GetProjectBySlug :one
SELECT id, company_name, employee_count, discovery_source, name, slug, description, logo_url, website_url, twitter_handle, discord_invite_link, treasury_wallet, blockchain, environment, token_address, token_name, token_symbol, created_at, updated_at FROM projects WHERE slug = $1
`

func (q *Queries) GetProjectBySlug(ctx context.Context, slug string) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectBySlug, slug)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.CompanyName,
		&i.EmployeeCount,
		&i.DiscoverySource,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.LogoUrl,
		&i.WebsiteUrl,
		&i.TwitterHandle,
		&i.DiscordInviteLink,
		&i.TreasuryWallet,
		&i.Blockchain,
		&i.Environment,
		&i.TokenAddress,
		&i.TokenName,
		&i.TokenSymbol,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects SET
    name               = COALESCE($2, name),
    description        = COALESCE($3, description),
    logo_url           = COALESCE($4, logo_url),
    website_url        = COALESCE($5, website_url),
    twitter_handle     = COALESCE($6, twitter_handle),
    discord_invite_link = COALESCE($7, discord_invite_link),
    updated_at         = NOW()
WHERE id = $1
RETURNING id, company_name, employee_count, discovery_source, name, slug, description, logo_url, website_url, twitter_handle, discord_invite_link, treasury_wallet, blockchain, environment, token_address, token_name, token_symbol, created_at, updated_at
`

type UpdateProjectParams struct {
	ID                pgtype.UUID `json:"id"`
	Name              string      `json:"name"`
	Description       pgtype.Text `json:"description"`
	LogoUrl           pgtype.Text `json:"logo_url"`
	WebsiteUrl        pgtype.Text `json:"website_url"`
	TwitterHandle     pgtype.Text `json:"twitter_handle"`
	DiscordInviteLink pgtype.Text `json:"discord_invite_link"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.LogoUrl,
		arg.WebsiteUrl,
		arg.TwitterHandle,
		arg.DiscordInviteLink,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.CompanyName,
		&i.EmployeeCount,
		&i.DiscoverySource,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.LogoUrl,
		&i.WebsiteUrl,
		&i.TwitterHandle,
		&i.DiscordInviteLink,
		&i.TreasuryWallet,
		&i.Blockchain,
		&i.Environment,
		&i.TokenAddress,
		&i.TokenName,
		&i.TokenSymbol,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProjectTokenInfo = `-- name: UpdateProjectTokenInfo :one
UPDATE projects SET
    token_address = $2,
    token_name    = $3,
    token_symbol  = $4,
    updated_at    = NOW()
WHERE id = $1
RETURNING id, company_name, employee_count, discovery_source, name, slug, description, logo_url, website_url, twitter_handle, discord_invite_link, treasury_wallet, blockchain, environment, token_address, token_name, token_symbol, created_at, updated_at
`

type UpdateProjectTokenInfoParams struct {
	ID           pgtype.UUID `json:"id"`
	TokenAddress string      `json:"token_address"`
	TokenName    pgtype.Text `json:"token_name"`
	TokenSymbol  pgtype.Text `json:"token_symbol"`
}

func (q *Queries) UpdateProjectTokenInfo(ctx context.Context, arg UpdateProjectTokenInfoParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProjectTokenInfo,
		arg.ID,
		arg.TokenAddress,
		arg.TokenName,
		arg.TokenSymbol,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.CompanyName,
		&i.EmployeeCount,
		&i.DiscoverySource,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.LogoUrl,
		&i.WebsiteUrl,
		&i.TwitterHandle,
		&i.DiscordInviteLink,
		&i.TreasuryWallet,
		&i.Blockchain,
		&i.Environment,
		&i.TokenAddress,
		&i.TokenName,
		&i.TokenSymbol,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
