// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project_members.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addProjectMember = `-- name: AddProjectMember :one
INSERT INTO project_members (project_id, user_id, role, status)
VALUES ($1, $2, $3, $4)
ON CONFLICT (project_id, user_id) DO UPDATE
    SET role = $3, status = $4, updated_at = NOW()
RETURNING id, project_id, user_id, role, status, created_at, updated_at
`

type AddProjectMemberParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	UserID    pgtype.UUID `json:"user_id"`
	Role      string      `json:"role"`
	Status    string      `json:"status"`
}

func (q *Queries) AddProjectMember(ctx context.Context, arg AddProjectMemberParams) (ProjectMember, error) {
	row := q.db.QueryRow(ctx, addProjectMember,
		arg.ProjectID,
		arg.UserID,
		arg.Role,
		arg.Status,
	)
	var i ProjectMember
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectMember = `-- name: GetProjectMember :one
SELECT id, project_id, user_id, role, status, created_at, updated_at FROM project_members
WHERE project_id = $1 AND user_id = $2
`

type GetProjectMemberParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetProjectMember(ctx context.Context, arg GetProjectMemberParams) (ProjectMember, error) {
	row := q.db.QueryRow(ctx, getProjectMember, arg.ProjectID, arg.UserID)
	var i ProjectMember
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectMembership = `-- name: GetProjectMembership :one
SELECT project_id, role
FROM project_members
WHERE user_id = $1 AND status = 'active'
LIMIT 1
`

type GetProjectMembershipRow struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Role      string      `json:"role"`
}

func (q *Queries) GetProjectMembership(ctx context.Context, userID pgtype.UUID) (GetProjectMembershipRow, error) {
	row := q.db.QueryRow(ctx, getProjectMembership, userID)
	var i GetProjectMembershipRow
	err := row.Scan(&i.ProjectID, &i.Role)
	return i, err
}

const listProjectMembers = `-- name: ListProjectMembers :many
SELECT pm.id, pm.project_id, pm.user_id, pm.role, pm.status, pm.created_at, pm.updated_at, u.wallet_address, u.display_name, u.avatar_url
FROM project_members pm
JOIN users u ON u.id = pm.user_id
WHERE pm.project_id = $1
ORDER BY pm.created_at ASC
`

type ListProjectMembersRow struct {
	ID            pgtype.UUID        `json:"id"`
	ProjectID     pgtype.UUID        `json:"project_id"`
	UserID        pgtype.UUID        `json:"user_id"`
	Role          string             `json:"role"`
	Status        string             `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	WalletAddress string             `json:"wallet_address"`
	DisplayName   pgtype.Text        `json:"display_name"`
	AvatarUrl     pgtype.Text        `json:"avatar_url"`
}

func (q *Queries) ListProjectMembers(ctx context.Context, projectID pgtype.UUID) ([]ListProjectMembersRow, error) {
	rows, err := q.db.Query(ctx, listProjectMembers, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectMembersRow{}
	for rows.Next() {
		var i ListProjectMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.UserID,
			&i.Role,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WalletAddress,
			&i.DisplayName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsForUser = `-- name: ListProjectsForUser :many
SELECT p.id, p.company_name, p.employee_count, p.discovery_source, p.name, p.slug, p.description, p.logo_url, p.website_url, p.twitter_handle, p.discord_invite_link, p.treasury_wallet, p.blockchain, p.environment, p.token_address, p.token_name, p.token_symbol, p.created_at, p.updated_at, pm.role, pm.status
FROM project_members pm
JOIN projects p ON p.id = pm.project_id
WHERE pm.user_id = $1 AND pm.status = 'active'
`

type ListProjectsForUserRow struct {
	ID                pgtype.UUID        `json:"id"`
	CompanyName       string             `json:"company_name"`
	EmployeeCount     pgtype.Text        `json:"employee_count"`
	DiscoverySource   pgtype.Text        `json:"discovery_source"`
	Name              string             `json:"name"`
	Slug              string             `json:"slug"`
	Description       pgtype.Text        `json:"description"`
	LogoUrl           pgtype.Text        `json:"logo_url"`
	WebsiteUrl        pgtype.Text        `json:"website_url"`
	TwitterHandle     pgtype.Text        `json:"twitter_handle"`
	DiscordInviteLink pgtype.Text        `json:"discord_invite_link"`
	TreasuryWallet    string             `json:"treasury_wallet"`
	Blockchain        string             `json:"blockchain"`
	Environment       string             `json:"environment"`
	TokenAddress      string             `json:"token_address"`
	TokenName         pgtype.Text        `json:"token_name"`
	TokenSymbol       pgtype.Text        `json:"token_symbol"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	Role              string             `json:"role"`
	Status            string             `json:"status"`
}

func (q *Queries) ListProjectsForUser(ctx context.Context, userID pgtype.UUID) ([]ListProjectsForUserRow, error) {
	rows, err := q.db.Query(ctx, listProjectsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectsForUserRow{}
	for rows.Next() {
		var i ListProjectsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyName,
			&i.EmployeeCount,
			&i.DiscoverySource,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.LogoUrl,
			&i.WebsiteUrl,
			&i.TwitterHandle,
			&i.DiscordInviteLink,
			&i.TreasuryWallet,
			&i.Blockchain,
			&i.Environment,
			&i.TokenAddress,
			&i.TokenName,
			&i.TokenSymbol,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Role,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeProjectMember = `-- name: RemoveProjectMember :exec
DELETE FROM project_members
WHERE project_id = $1 AND user_id = $2
`

type RemoveProjectMemberParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) RemoveProjectMember(ctx context.Context, arg RemoveProjectMemberParams) error {
	_, err := q.db.Exec(ctx, removeProjectMember, arg.ProjectID, arg.UserID)
	return err
}

const updateMemberRole = `-- name: UpdateMemberRole :one
UPDATE project_members
SET role = $3, updated_at = NOW()
WHERE project_id = $1 AND user_id = $2
RETURNING id, project_id, user_id, role, status, created_at, updated_at
`

type UpdateMemberRoleParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	UserID    pgtype.UUID `json:"user_id"`
	Role      string      `json:"role"`
}

func (q *Queries) UpdateMemberRole(ctx context.Context, arg UpdateMemberRoleParams) (ProjectMember, error) {
	row := q.db.QueryRow(ctx, updateMemberRole, arg.ProjectID, arg.UserID, arg.Role)
	var i ProjectMember
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMemberStatus = `-- name: UpdateMemberStatus :one
UPDATE project_members
SET status = $3, updated_at = NOW()
WHERE project_id = $1 AND user_id = $2
RETURNING id, project_id, user_id, role, status, created_at, updated_at
`

type UpdateMemberStatusParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	UserID    pgtype.UUID `json:"user_id"`
	Status    string      `json:"status"`
}

func (q *Queries) UpdateMemberStatus(ctx context.Context, arg UpdateMemberStatusParams) (ProjectMember, error) {
	row := q.db.QueryRow(ctx, updateMemberStatus, arg.ProjectID, arg.UserID, arg.Status)
	var i ProjectMember
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
