// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project_api_keys.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO project_api_keys (project_id, name, key_hash, key_hint)
VALUES ($1, $2, $3, $4)
RETURNING id, project_id, name, key_hash, key_hint, is_active, created_at, last_used_at
`

type CreateAPIKeyParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Name      string      `json:"name"`
	KeyHash   string      `json:"key_hash"`
	KeyHint   string      `json:"key_hint"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ProjectApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.ProjectID,
		arg.Name,
		arg.KeyHash,
		arg.KeyHint,
	)
	var i ProjectApiKey
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.KeyHash,
		&i.KeyHint,
		&i.IsActive,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT id, project_id, name, key_hash, key_hint, is_active, created_at, last_used_at FROM project_api_keys
WHERE key_hash = $1 AND is_active = TRUE
`

func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash string) (ProjectApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByHash, keyHash)
	var i ProjectApiKey
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.KeyHash,
		&i.KeyHint,
		&i.IsActive,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const listAPIKeysByOrg = `-- name: ListAPIKeysByOrg :many
SELECT id, project_id, name, key_hash, key_hint, is_active, created_at, last_used_at FROM project_api_keys
WHERE project_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListAPIKeysByOrg(ctx context.Context, projectID pgtype.UUID) ([]ProjectApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeysByOrg, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectApiKey{}
	for rows.Next() {
		var i ProjectApiKey
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.KeyHash,
			&i.KeyHint,
			&i.IsActive,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :exec
UPDATE project_api_keys
SET is_active = FALSE
WHERE id = $1 AND project_id = $2
`

type RevokeAPIKeyParams struct {
	ID        pgtype.UUID `json:"id"`
	ProjectID pgtype.UUID `json:"project_id"`
}

func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) error {
	_, err := q.db.Exec(ctx, revokeAPIKey, arg.ID, arg.ProjectID)
	return err
}

const touchAPIKeyUsage = `-- name: TouchAPIKeyUsage :exec
UPDATE project_api_keys
SET last_used_at = NOW()
WHERE id = $1
`

func (q *Queries) TouchAPIKeyUsage(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchAPIKeyUsage, id)
	return err
}
