// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddProjectMember(ctx context.Context, arg AddProjectMemberParams) (ProjectMember, error)
	CountTasksByCampaign(ctx context.Context, campaignID pgtype.UUID) (int64, error)
	CountVerifiedTasksForUser(ctx context.Context, arg CountVerifiedTasksForUserParams) (int64, error)
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ProjectApiKey, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error)
	CreateCampaign(ctx context.Context, arg CreateCampaignParams) (Campaign, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteExpiredNonces(ctx context.Context) error
	DeleteNonce(ctx context.Context, walletAddress string) error
	FinalizeCampaign(ctx context.Context, arg FinalizeCampaignParams) (Campaign, error)
	GetAPIKeyByHash(ctx context.Context, keyHash string) (ProjectApiKey, error)
	GetCampaignByID(ctx context.Context, id pgtype.UUID) (Campaign, error)
	GetCampaignBySlug(ctx context.Context, slug string) (Campaign, error)
	GetCompletion(ctx context.Context, arg GetCompletionParams) (TaskCompletion, error)
	GetCompletionSpeedSeconds(ctx context.Context, arg GetCompletionSpeedSecondsParams) (int32, error)
	GetLatestSnapshot(ctx context.Context, campaignID pgtype.UUID) (CampaignAnalyticsSnapshot, error)
	GetNonce(ctx context.Context, walletAddress string) (AuthNonce, error)
	GetProjectByID(ctx context.Context, id pgtype.UUID) (Project, error)
	GetProjectBySlug(ctx context.Context, slug string) (Project, error)
	GetProjectMember(ctx context.Context, arg GetProjectMemberParams) (ProjectMember, error)
	GetProjectMembership(ctx context.Context, userID pgtype.UUID) (GetProjectMembershipRow, error)
	GetTask(ctx context.Context, id pgtype.UUID) (Task, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByWallet(ctx context.Context, walletAddress string) (User, error)
	GetUserPointsForCampaign(ctx context.Context, arg GetUserPointsForCampaignParams) (int32, error)
	IncrementClaimedAmount(ctx context.Context, arg IncrementClaimedAmountParams) (Campaign, error)
	InsertAnalyticsSnapshot(ctx context.Context, arg InsertAnalyticsSnapshotParams) (CampaignAnalyticsSnapshot, error)
	ListAPIKeysByOrg(ctx context.Context, projectID pgtype.UUID) ([]ProjectApiKey, error)
	ListActiveCampaigns(ctx context.Context, arg ListActiveCampaignsParams) ([]Campaign, error)
	ListAuditLogsByEntity(ctx context.Context, arg ListAuditLogsByEntityParams) ([]AuditLog, error)
	ListAuditLogsByProject(ctx context.Context, arg ListAuditLogsByProjectParams) ([]ListAuditLogsByProjectRow, error)
	ListCampaignLeaderboard(ctx context.Context, arg ListCampaignLeaderboardParams) ([]ListCampaignLeaderboardRow, error)
	ListCampaignsByProject(ctx context.Context, projectID pgtype.UUID) ([]Campaign, error)
	ListCompletionsByUserAndCampaign(ctx context.Context, arg ListCompletionsByUserAndCampaignParams) ([]ListCompletionsByUserAndCampaignRow, error)
	ListProjectMembers(ctx context.Context, projectID pgtype.UUID) ([]ListProjectMembersRow, error)
	ListProjectsForUser(ctx context.Context, userID pgtype.UUID) ([]ListProjectsForUserRow, error)
	ListSnapshotsByCampaign(ctx context.Context, campaignID pgtype.UUID) ([]CampaignAnalyticsSnapshot, error)
	ListSnapshotsInRange(ctx context.Context, arg ListSnapshotsInRangeParams) ([]CampaignAnalyticsSnapshot, error)
	ListTasksByCampaign(ctx context.Context, campaignID pgtype.UUID) ([]Task, error)
	RemoveProjectMember(ctx context.Context, arg RemoveProjectMemberParams) error
	RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) error
	SoftDeleteCampaign(ctx context.Context, id pgtype.UUID) error
	SoftDeleteTask(ctx context.Context, arg SoftDeleteTaskParams) error
	TouchAPIKeyUsage(ctx context.Context, id pgtype.UUID) error
	TouchLastSeen(ctx context.Context, id pgtype.UUID) error
	UpdateCampaign(ctx context.Context, arg UpdateCampaignParams) (Campaign, error)
	UpdateCampaignStatus(ctx context.Context, arg UpdateCampaignStatusParams) (Campaign, error)
	UpdateMemberRole(ctx context.Context, arg UpdateMemberRoleParams) (ProjectMember, error)
	UpdateMemberStatus(ctx context.Context, arg UpdateMemberStatusParams) (ProjectMember, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UpdateProjectTokenInfo(ctx context.Context, arg UpdateProjectTokenInfoParams) (Project, error)
	UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
	UpsertCompletion(ctx context.Context, arg UpsertCompletionParams) (TaskCompletion, error)
	UpsertDiscord(ctx context.Context, arg UpsertDiscordParams) (User, error)
	UpsertNonce(ctx context.Context, arg UpsertNonceParams) (AuthNonce, error)
	UpsertTwitter(ctx context.Context, arg UpsertTwitterParams) (User, error)
}

var _ Querier = (*Queries)(nil)
