// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task_completions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countVerifiedTasksForUser = `-- name: CountVerifiedTasksForUser :one
SELECT COUNT(*) FROM task_completions
WHERE campaign_id = $1 AND user_id = $2 AND status = 'verified'
`

type CountVerifiedTasksForUserParams struct {
	CampaignID pgtype.UUID `json:"campaign_id"`
	UserID     pgtype.UUID `json:"user_id"`
}

func (q *Queries) CountVerifiedTasksForUser(ctx context.Context, arg CountVerifiedTasksForUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countVerifiedTasksForUser, arg.CampaignID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCompletion = `-- name: GetCompletion :one
SELECT id, user_id, task_id, campaign_id, status, points_earned, proof, completed_at FROM task_completions
WHERE user_id = $1 AND task_id = $2
`

type GetCompletionParams struct {
	UserID pgtype.UUID `json:"user_id"`
	TaskID pgtype.UUID `json:"task_id"`
}

func (q *Queries) GetCompletion(ctx context.Context, arg GetCompletionParams) (TaskCompletion, error) {
	row := q.db.QueryRow(ctx, getCompletion, arg.UserID, arg.TaskID)
	var i TaskCompletion
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TaskID,
		&i.CampaignID,
		&i.Status,
		&i.PointsEarned,
		&i.Proof,
		&i.CompletedAt,
	)
	return i, err
}

const getCompletionSpeedSeconds = `-- name: GetCompletionSpeedSeconds :one
SELECT EXTRACT(EPOCH FROM (MAX(completed_at) - MIN(completed_at)))::INT AS seconds
FROM task_completions
WHERE campaign_id = $1 AND user_id = $2 AND status = 'verified'
`

type GetCompletionSpeedSecondsParams struct {
	CampaignID pgtype.UUID `json:"campaign_id"`
	UserID     pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetCompletionSpeedSeconds(ctx context.Context, arg GetCompletionSpeedSecondsParams) (int32, error) {
	row := q.db.QueryRow(ctx, getCompletionSpeedSeconds, arg.CampaignID, arg.UserID)
	var seconds int32
	err := row.Scan(&seconds)
	return seconds, err
}

const getUserPointsForCampaign = `-- name: GetUserPointsForCampaign :one
SELECT COALESCE(SUM(points_earned), 0)::INT AS total_points
FROM task_completions
WHERE campaign_id = $1 AND user_id = $2 AND status = 'verified'
`

type GetUserPointsForCampaignParams struct {
	CampaignID pgtype.UUID `json:"campaign_id"`
	UserID     pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetUserPointsForCampaign(ctx context.Context, arg GetUserPointsForCampaignParams) (int32, error) {
	row := q.db.QueryRow(ctx, getUserPointsForCampaign, arg.CampaignID, arg.UserID)
	var total_points int32
	err := row.Scan(&total_points)
	return total_points, err
}

const listCampaignLeaderboard = `-- name: ListCampaignLeaderboard :many
SELECT user_id, SUM(points_earned)::INT AS total_points
FROM task_completions
WHERE campaign_id = $1 AND status = 'verified'
GROUP BY user_id
ORDER BY total_points DESC
LIMIT $2 OFFSET $3
`

type ListCampaignLeaderboardParams struct {
	CampaignID pgtype.UUID `json:"campaign_id"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
}

type ListCampaignLeaderboardRow struct {
	UserID      pgtype.UUID `json:"user_id"`
	TotalPoints int32       `json:"total_points"`
}

func (q *Queries) ListCampaignLeaderboard(ctx context.Context, arg ListCampaignLeaderboardParams) ([]ListCampaignLeaderboardRow, error) {
	rows, err := q.db.Query(ctx, listCampaignLeaderboard, arg.CampaignID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCampaignLeaderboardRow{}
	for rows.Next() {
		var i ListCampaignLeaderboardRow
		if err := rows.Scan(&i.UserID, &i.TotalPoints); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompletionsByUserAndCampaign = `-- name: ListCompletionsByUserAndCampaign :many
SELECT tc.id, tc.user_id, tc.task_id, tc.campaign_id, tc.status, tc.points_earned, tc.proof, tc.completed_at, t.points AS task_points, t.is_required, t.title AS task_title
FROM task_completions tc
JOIN tasks t ON t.id = tc.task_id
WHERE tc.campaign_id = $1 AND tc.user_id = $2
`

type ListCompletionsByUserAndCampaignParams struct {
	CampaignID pgtype.UUID `json:"campaign_id"`
	UserID     pgtype.UUID `json:"user_id"`
}

type ListCompletionsByUserAndCampaignRow struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	TaskID       pgtype.UUID        `json:"task_id"`
	CampaignID   pgtype.UUID        `json:"campaign_id"`
	Status       CompletionStatus   `json:"status"`
	PointsEarned int32              `json:"points_earned"`
	Proof        []byte             `json:"proof"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
	TaskPoints   int32              `json:"task_points"`
	IsRequired   bool               `json:"is_required"`
	TaskTitle    string             `json:"task_title"`
}

func (q *Queries) ListCompletionsByUserAndCampaign(ctx context.Context, arg ListCompletionsByUserAndCampaignParams) ([]ListCompletionsByUserAndCampaignRow, error) {
	rows, err := q.db.Query(ctx, listCompletionsByUserAndCampaign, arg.CampaignID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCompletionsByUserAndCampaignRow{}
	for rows.Next() {
		var i ListCompletionsByUserAndCampaignRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TaskID,
			&i.CampaignID,
			&i.Status,
			&i.PointsEarned,
			&i.Proof,
			&i.CompletedAt,
			&i.TaskPoints,
			&i.IsRequired,
			&i.TaskTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCompletion = `-- name: UpsertCompletion :one
INSERT INTO task_completions (user_id, task_id, campaign_id, status, points_earned, proof)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (user_id, task_id) DO UPDATE
    SET status = $4, points_earned = $5, proof = $6, completed_at = NOW()
RETURNING id, user_id, task_id, campaign_id, status, points_earned, proof, completed_at
`

type UpsertCompletionParams struct {
	UserID       pgtype.UUID      `json:"user_id"`
	TaskID       pgtype.UUID      `json:"task_id"`
	CampaignID   pgtype.UUID      `json:"campaign_id"`
	Status       CompletionStatus `json:"status"`
	PointsEarned int32            `json:"points_earned"`
	Proof        []byte           `json:"proof"`
}

func (q *Queries) UpsertCompletion(ctx context.Context, arg UpsertCompletionParams) (TaskCompletion, error) {
	row := q.db.QueryRow(ctx, upsertCompletion,
		arg.UserID,
		arg.TaskID,
		arg.CampaignID,
		arg.Status,
		arg.PointsEarned,
		arg.Proof,
	)
	var i TaskCompletion
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TaskID,
		&i.CampaignID,
		&i.Status,
		&i.PointsEarned,
		&i.Proof,
		&i.CompletedAt,
	)
	return i, err
}
