// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTasksByCampaign = `-- name: CountTasksByCampaign :one
SELECT COUNT(*) FROM tasks
WHERE campaign_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountTasksByCampaign(ctx context.Context, campaignID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTasksByCampaign, campaignID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (campaign_id, title, description, task_type, verification_type, config, points, is_required, display_order)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, campaign_id, title, description, task_type, verification_type, config, points, is_required, display_order, deleted_at, created_at, updated_at
`

type CreateTaskParams struct {
	CampaignID       pgtype.UUID `json:"campaign_id"`
	Title            string      `json:"title"`
	Description      pgtype.Text `json:"description"`
	TaskType         string      `json:"task_type"`
	VerificationType string      `json:"verification_type"`
	Config           []byte      `json:"config"`
	Points           int32       `json:"points"`
	IsRequired       bool        `json:"is_required"`
	DisplayOrder     int32       `json:"display_order"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.CampaignID,
		arg.Title,
		arg.Description,
		arg.TaskType,
		arg.VerificationType,
		arg.Config,
		arg.Points,
		arg.IsRequired,
		arg.DisplayOrder,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Title,
		&i.Description,
		&i.TaskType,
		&i.VerificationType,
		&i.Config,
		&i.Points,
		&i.IsRequired,
		&i.DisplayOrder,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTask = `-- name: GetTask :one
SELECT id, campaign_id, title, description, task_type, verification_type, config, points, is_required, display_order, deleted_at, created_at, updated_at FROM tasks
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetTask(ctx context.Context, id pgtype.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Title,
		&i.Description,
		&i.TaskType,
		&i.VerificationType,
		&i.Config,
		&i.Points,
		&i.IsRequired,
		&i.DisplayOrder,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTasksByCampaign = `-- name: ListTasksByCampaign :many
SELECT id, campaign_id, title, description, task_type, verification_type, config, points, is_required, display_order, deleted_at, created_at, updated_at FROM tasks
WHERE campaign_id = $1 AND deleted_at IS NULL
ORDER BY display_order ASC
`

func (q *Queries) ListTasksByCampaign(ctx context.Context, campaignID pgtype.UUID) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasksByCampaign, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.Title,
			&i.Description,
			&i.TaskType,
			&i.VerificationType,
			&i.Config,
			&i.Points,
			&i.IsRequired,
			&i.DisplayOrder,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTask = `-- name: SoftDeleteTask :exec
UPDATE tasks
SET deleted_at = NOW()
WHERE id = $1 AND campaign_id = $2
`

type SoftDeleteTaskParams struct {
	ID         pgtype.UUID `json:"id"`
	CampaignID pgtype.UUID `json:"campaign_id"`
}

func (q *Queries) SoftDeleteTask(ctx context.Context, arg SoftDeleteTaskParams) error {
	_, err := q.db.Exec(ctx, softDeleteTask, arg.ID, arg.CampaignID)
	return err
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks SET
    title             = COALESCE($2, title),   -- COALESCE : evaluates a list of arguments and returns first non NULL value
    description       = COALESCE($3, description),
    config            = COALESCE($4, config),
    points            = COALESCE($5, points),
    is_required       = COALESCE($6, is_required),
    display_order     = COALESCE($7, display_order),
    updated_at        = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, campaign_id, title, description, task_type, verification_type, config, points, is_required, display_order, deleted_at, created_at, updated_at
`

type UpdateTaskParams struct {
	ID           pgtype.UUID `json:"id"`
	Title        string      `json:"title"`
	Description  pgtype.Text `json:"description"`
	Config       []byte      `json:"config"`
	Points       int32       `json:"points"`
	IsRequired   bool        `json:"is_required"`
	DisplayOrder int32       `json:"display_order"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Config,
		arg.Points,
		arg.IsRequired,
		arg.DisplayOrder,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Title,
		&i.Description,
		&i.TaskType,
		&i.VerificationType,
		&i.Config,
		&i.Points,
		&i.IsRequired,
		&i.DisplayOrder,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
