// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (wallet_address, ens_name, display_name, avatar_url)
VALUES ($1, $2, $3, $4)
ON CONFLICT (wallet_address) DO UPDATE
SET last_seen = NOW()
RETURNING id, wallet_address, ens_name, display_name, avatar_url, user_type, twitter_id, twitter_handle, discord_id, discord_handle, discord_token, created_at, updated_at, last_seen
`

type CreateUserParams struct {
	WalletAddress string      `json:"wallet_address"`
	EnsName       pgtype.Text `json:"ens_name"`
	DisplayName   pgtype.Text `json:"display_name"`
	AvatarUrl     pgtype.Text `json:"avatar_url"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.WalletAddress,
		arg.EnsName,
		arg.DisplayName,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.WalletAddress,
		&i.EnsName,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.UserType,
		&i.TwitterID,
		&i.TwitterHandle,
		&i.DiscordID,
		&i.DiscordHandle,
		&i.DiscordToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSeen,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, wallet_address, ens_name, display_name, avatar_url, user_type, twitter_id, twitter_handle, discord_id, discord_handle, discord_token, created_at, updated_at, last_seen FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.WalletAddress,
		&i.EnsName,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.UserType,
		&i.TwitterID,
		&i.TwitterHandle,
		&i.DiscordID,
		&i.DiscordHandle,
		&i.DiscordToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSeen,
	)
	return i, err
}

const getUserByWallet = `-- name: GetUserByWallet :one
SELECT id, wallet_address, ens_name, display_name, avatar_url, user_type, twitter_id, twitter_handle, discord_id, discord_handle, discord_token, created_at, updated_at, last_seen FROM users WHERE wallet_address = $1
`

func (q *Queries) GetUserByWallet(ctx context.Context, walletAddress string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByWallet, walletAddress)
	var i User
	err := row.Scan(
		&i.ID,
		&i.WalletAddress,
		&i.EnsName,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.UserType,
		&i.TwitterID,
		&i.TwitterHandle,
		&i.DiscordID,
		&i.DiscordHandle,
		&i.DiscordToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSeen,
	)
	return i, err
}

const touchLastSeen = `-- name: TouchLastSeen :exec
UPDATE users SET last_seen = NOW() WHERE id = $1
`

func (q *Queries) TouchLastSeen(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchLastSeen, id)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET display_name = $2, avatar_url = $3, ens_name = $4, updated_at = NOW()
WHERE id = $1
RETURNING id, wallet_address, ens_name, display_name, avatar_url, user_type, twitter_id, twitter_handle, discord_id, discord_handle, discord_token, created_at, updated_at, last_seen
`

type UpdateUserProfileParams struct {
	ID          pgtype.UUID `json:"id"`
	DisplayName pgtype.Text `json:"display_name"`
	AvatarUrl   pgtype.Text `json:"avatar_url"`
	EnsName     pgtype.Text `json:"ens_name"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.ID,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.EnsName,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.WalletAddress,
		&i.EnsName,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.UserType,
		&i.TwitterID,
		&i.TwitterHandle,
		&i.DiscordID,
		&i.DiscordHandle,
		&i.DiscordToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSeen,
	)
	return i, err
}

const upsertDiscord = `-- name: UpsertDiscord :one
UPDATE users
SET discord_id = $2, discord_handle = $3, discord_token = $4, updated_at = NOW()
WHERE id = $1
RETURNING id, wallet_address, ens_name, display_name, avatar_url, user_type, twitter_id, twitter_handle, discord_id, discord_handle, discord_token, created_at, updated_at, last_seen
`

type UpsertDiscordParams struct {
	ID            pgtype.UUID `json:"id"`
	DiscordID     pgtype.Text `json:"discord_id"`
	DiscordHandle pgtype.Text `json:"discord_handle"`
	DiscordToken  pgtype.Text `json:"discord_token"`
}

func (q *Queries) UpsertDiscord(ctx context.Context, arg UpsertDiscordParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertDiscord,
		arg.ID,
		arg.DiscordID,
		arg.DiscordHandle,
		arg.DiscordToken,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.WalletAddress,
		&i.EnsName,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.UserType,
		&i.TwitterID,
		&i.TwitterHandle,
		&i.DiscordID,
		&i.DiscordHandle,
		&i.DiscordToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSeen,
	)
	return i, err
}

const upsertTwitter = `-- name: UpsertTwitter :one
UPDATE users
SET twitter_id = $2, twitter_handle = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, wallet_address, ens_name, display_name, avatar_url, user_type, twitter_id, twitter_handle, discord_id, discord_handle, discord_token, created_at, updated_at, last_seen
`

type UpsertTwitterParams struct {
	ID            pgtype.UUID `json:"id"`
	TwitterID     pgtype.Text `json:"twitter_id"`
	TwitterHandle pgtype.Text `json:"twitter_handle"`
}

func (q *Queries) UpsertTwitter(ctx context.Context, arg UpsertTwitterParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertTwitter, arg.ID, arg.TwitterID, arg.TwitterHandle)
	var i User
	err := row.Scan(
		&i.ID,
		&i.WalletAddress,
		&i.EnsName,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.UserType,
		&i.TwitterID,
		&i.TwitterHandle,
		&i.DiscordID,
		&i.DiscordHandle,
		&i.DiscordToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSeen,
	)
	return i, err
}
